Repository COS301-SE-2022/The-Au-Pair, pull requests merged in 2022-06, with the labels that each got.

#85 ✨ (Feature): Static Au Pair screen and basic modal
  apps/the-au-pair/src/index.html
  apps/the-au-pair/src/styles.scss
  libs/au-pair-schedule/feature/.eslintrc.json
  libs/au-pair-schedule/feature/README.md
  libs/au-pair-schedule/feature/jest.config.js
  libs/au-pair-schedule/feature/project.json
  libs/au-pair-schedule/feature/src/index.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule-routing.module.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.scss
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.spec.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.module.ts
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.html
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.scss
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.spec.ts
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.ts
  libs/au-pair-schedule/feature/src/test-setup.ts
  libs/au-pair-schedule/feature/tsconfig.json
  libs/au-pair-schedule/feature/tsconfig.lib.json
  libs/au-pair-schedule/feature/tsconfig.spec.json
  libs/shell/feature/src/lib/shell-routing.module.ts
  tsconfig.base.json
  workspace.json
Labels: scope:ui, scope:client, priority:medium, status:ready, type:feature

#97 ✨(feature):Activity comments and ratings
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.html
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.scss
Labels: scope:ui, scope:client, priority:high, status:ready, type:feature

#104 🎨(API) : Restructure of backend
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
  Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
  Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
  Server/src/main/java/Database/TheAuPair/Services/ChildService.java
  Server/src/main/java/Database/TheAuPair/Services/ParentService.java
  Server/src/main/java/Database/TheAuPair/Services/UserService.java
  Server/src/main/java/Database/TheAuPair/Services/auPairService.java
  Server/src/main/java/Database/TheAuPair/Services/medAidService.java
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
Labels: scope:api, priority:high, status:ready, type:change

#114 ✨(API) : Added functions for Activity Service
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
  libs/shared/api/api.service.ts
Labels: scope:api, priority:high, status:ready, type:feature

#116 💚(CI/CD) : Fixed install of node
  .github/workflows/CI.yml
Labels: scope:cicd, priority:high, status:ready, type:fix

#115 ✨(API) : Added functions for Children Service
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ChildService.java
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: scope:api, priority:high, status:ready, type:feature

#117 ✨(API) : Added functions for Activity Service
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Models/Activity.java
  Server/src/main/java/Database/TheAuPair/Models/Child.java
  Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
  libs/shared/api/api.service.ts
Labels: scope:api, priority:high, status:ready, type:feature

#122 ✨(API) : Added functions for Parent, User and MedicalAid Service
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
  Server/src/main/java/Database/TheAuPair/Repositories/medAidRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ParentService.java
  Server/src/main/java/Database/TheAuPair/Services/UserService.java
  Server/src/main/java/Database/TheAuPair/Services/medAidService.java
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: scope:api, priority:high, status:ready, type:feature

#125 🎨(API) : Code Cleanup
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
  Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
  Server/src/main/java/Database/TheAuPair/Models/Child.java
  Server/src/main/java/Database/TheAuPair/Models/auPair.java
  Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/auPairRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
  Server/src/main/java/Database/TheAuPair/Services/ParentService.java
  Server/src/main/java/Database/TheAuPair/Services/UserService.java
  Server/src/main/java/Database/TheAuPair/Services/auPairService.java
  Server/src/main/java/Database/TheAuPair/Services/medAidService.java
  Server/src/test/java/Database/TheAuPair/auPairRepositoryTests.java
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/schedule/feature/src/lib/schedule.ts
  libs/shared/api/api.service.ts
Labels: scope:admin, priority:high, status:ready, type:fix

#127 Created Logging Hours API
  Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
  Server/src/main/java/Database/TheAuPair/Models/hoursLogged.java
  Server/src/main/java/Database/TheAuPair/Repositories/hoursLoggedRepository.java
  Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: scope:api, scope:database, scope:repository, priority:high, status:ready, type:feature

#124 👽️✅ (API + testing): API usage & unit/integration tests for edit activity page
  apps/the-au-pair/src/styles.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.spec.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.ts
Labels: type:enhancement, scope:ui, scope:api, scope:tests, scope:client, priority:high, status:ready, type:tests

#129 👽️(API) : Updated MedicalAid Model
  Server/src/main/java/Database/TheAuPair/Models/medAid.java
Labels: scope:api, scope:database, priority:low, status:ready, type:change

#132 👽️(API) : updated Child model and functions
  Server/src/main/java/Database/TheAuPair/Models/Child.java
  Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ChildService.java
Labels: type:enhancement, scope:api, priority:medium, status:ready

#133 👽️✅ (API + tests): Add Child page integrated with API, Unit + Integration tests complete.
  libs/add-child/feature/src/lib/add-child.component.html
  libs/add-child/feature/src/lib/add-child.component.scss
  libs/add-child/feature/src/lib/add-child.component.spec.ts
  libs/add-child/feature/src/lib/add-child.component.ts
Labels: type:enhancement, scope:ui, scope:api, scope:tests, scope:client, priority:high, status:ready, type:tests

#134 👽️💄 (API + Styling) : API for children dashboard and styling for mobile view
  libs/children-dashboard/feature/src/lib/children-dashboard-feature.module.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.html
  libs/children-dashboard/feature/src/lib/children-dashboard.component.scss
  libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
Labels: type:enhancement, scope:ui, scope:api, scope:client, priority:high, status:ready

#131 ✨ (API + Frontend) Added dynamic hour functionality to Au Pair Costs Page
  Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
  Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.html
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
  libs/shared/api/api.service.ts
Labels: type:enhancement, scope:ui, scope:api, scope:client, priority:high, status:ready, type:change, type:feature

#137 👽️(API) : Updated Activity model
  Server/src/main/java/Database/TheAuPair/Models/Activity.java
Labels: scope:api, priority:low, status:ready, type:change

#140 👽️(API) : updated activity interface
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.spec.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/shared/interfaces/interfaces.ts
Labels: scope:api, priority:high, status:ready, type:change

#141 👽️ (API): Update Parents in the DB to have the new added child
  libs/add-child/feature/src/lib/add-child.component.ts
  libs/shared/interfaces/interfaces.ts
Labels: type:enhancement, scope:ui, scope:api, scope:client, priority:medium, status:ready

#138 ✨(UI, API, Tests): Created Parent Profile Feature
  libs/edit-parent-profile/feature/.eslintrc.json
  libs/edit-parent-profile/feature/README.md
  libs/edit-parent-profile/feature/jest.config.js
  libs/edit-parent-profile/feature/project.json
  libs/edit-parent-profile/feature/src/index.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile-feature.module.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile-routing.module.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.html
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.scss
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.spec.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.ts
  libs/edit-parent-profile/feature/src/test-setup.ts
  libs/edit-parent-profile/feature/tsconfig.json
  libs/edit-parent-profile/feature/tsconfig.lib.json
  libs/edit-parent-profile/feature/tsconfig.spec.json
  libs/parent-dashboard/feature/src/lib/parent-dashboard-feature.module.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-profile/feature/.eslintrc.json
  libs/parent-profile/feature/README.md
  libs/parent-profile/feature/jest.config.js
  libs/parent-profile/feature/project.json
  libs/parent-profile/feature/src/index.ts
  libs/parent-profile/feature/src/lib/parent-profile-feature.module.ts
  libs/parent-profile/feature/src/lib/parent-profile-routing.module.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.html
  libs/parent-profile/feature/src/lib/parent-profile.component.scss
  libs/parent-profile/feature/src/lib/parent-profile.component.spec.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.ts
  libs/parent-profile/feature/src/test-setup.ts
  libs/parent-profile/feature/tsconfig.json
  libs/parent-profile/feature/tsconfig.lib.json
  libs/parent-profile/feature/tsconfig.spec.json
  libs/shared/components/navbar/src/lib/navbar.component.html
  libs/shared/interfaces/interfaces.ts
  libs/shell/feature/src/lib/shell-routing.module.ts
  tsconfig.base.json
  workspace.json
Labels: scope:ui, scope:api, scope:tests, priority:high, status:ready, type:feature

#142 ✨ (UI + API) Added logging button for Au Pairs
  Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
  Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
  apps/the-au-pair/src/theme/variables.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: type:enhancement, scope:ui, scope:api, scope:tests, priority:high, status:ready, type:change, type:feature

#163 🩹 (FIX) : Au Pair Navbar
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.module.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/shared/components/aupair-navbar/.eslintrc.json
  libs/shared/components/aupair-navbar/README.md
  libs/shared/components/aupair-navbar/jest.config.js
  libs/shared/components/aupair-navbar/project.json
  libs/shared/components/aupair-navbar/src/index.ts
  libs/shared/components/aupair-navbar/src/lib/navbar.component.html
  libs/shared/components/aupair-navbar/src/lib/navbar.component.scss
  libs/shared/components/aupair-navbar/src/lib/navbar.component.spec.ts
  libs/shared/components/aupair-navbar/src/lib/navbar.component.ts
  libs/shared/components/aupair-navbar/src/lib/navbar.module.ts
  libs/shared/components/aupair-navbar/src/test-setup.ts
  libs/shared/components/aupair-navbar/tsconfig.json
  libs/shared/components/aupair-navbar/tsconfig.lib.json
  libs/shared/components/aupair-navbar/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: scope:ui, scope:client, priority:medium, status:ready, type:change, type:fix

#166 🚑(UI + Tests) Fix for testing and logging button
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.spec.ts
Labels: scope:ui, scope:tests, priority:high, status:ready, type:bug, type:fix

#171 ✨(feature): Added a view activity page for a parent
  libs/parent-view-activity/feature/.eslintrc.json
  libs/parent-view-activity/feature/README.md
  libs/parent-view-activity/feature/jest.config.js
  libs/parent-view-activity/feature/project.json
  libs/parent-view-activity/feature/src/index.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity-feature.module.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity-routing.module.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.html
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.scss
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.spec.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.ts
  libs/parent-view-activity/feature/src/test-setup.ts
  libs/parent-view-activity/feature/tsconfig.json
  libs/parent-view-activity/feature/tsconfig.lib.json
  libs/parent-view-activity/feature/tsconfig.spec.json
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.ts
  libs/shell/feature/src/lib/shell-routing.module.ts
  tsconfig.base.json
  workspace.json
Labels: scope:ui, priority:high, status:ready, type:feature

#172 🩹(fix): UI touchup
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard-feature.module.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.scss
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.spec.ts
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.html
  libs/children-dashboard/feature/src/lib/children-dashboard.component.html
  libs/children-dashboard/feature/src/lib/children-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-profile/feature/src/lib/parent-profile.component.html
  libs/parent-profile/feature/src/lib/parent-profile.component.spec.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/shared/components/aupair-navbar/src/lib/navbar.component.html
  libs/shared/components/aupair-navbar/src/lib/navbar.component.spec.ts
  libs/shared/components/navbar/src/lib/navbar.component.html
  libs/shared/components/navbar/src/lib/navbar.component.spec.ts
Labels: scope:ui, scope:client, priority:high, status:ready, type:feature, type:fix

#173 🚑️ (Hot fix): Fixes for for back-end test
  Server/src/test/java/Database/TheAuPair/ChildRepositoryTests.java
Labels: scope:tests, priority:high, status:ready, type:fix, type:tests

#174 🚑️(Hot Fix) : Fixes for backend tests
  Server/src/test/java/Database/TheAuPair/ChildRepositoryTests.java
Labels: scope:tests, priority:high, status:ready, type:fix
