Repository COS301-SE-2022/The-Au-Pair, pull requests merged in 2022-09, with the labels that each got.

#273 (💄✅) : New field for activities and UI fixes for activity/children pages
  Server/src/main/java/Database/TheAuPair/Models/Activity.java
  apps/the-au-pair/src/app/app.component.ts
  libs/add-child/feature/src/lib/add-child.component.html
  libs/add-child/feature/src/lib/add-child.component.scss
  libs/add-child/feature/src/lib/add-child.component.spec.ts
  libs/add-child/feature/src/lib/add-child.component.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.html
  libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
  libs/edit-child/feature/src/lib/edit-child.component.html
  libs/edit-child/feature/src/lib/edit-child.component.scss
  libs/explore/feature/src/lib/explore.component.scss
  libs/hire-requests/feature/src/lib/hire-requests.component.scss
  libs/notifications/feature/src/lib/notifications.component.scss
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.spec.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.html
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.scss
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/shared/interfaces/interfaces.ts
Labels: type:enhancement, scope:ui, scope:tests, scope:client, priority:medium, status:ready

#285 Route Protection: Auth Guard Service
  apps/the-au-pair/src/app/app.module.ts
  apps/the-au-pair/src/index.html
  libs/login/feature/src/lib/login.component.ts
  libs/shared/ngxs/actions.ts
  libs/shared/ngxs/state.ts
  libs/shared/services/auth/.eslintrc.json
  libs/shared/services/auth/jest.config.js
  libs/shared/services/auth/project.json
  libs/shared/services/auth/src/auth-guard.spec.ts
  libs/shared/services/auth/src/auth-guard.ts
  libs/shared/services/auth/src/index.ts
  libs/shared/services/auth/src/test-setup.ts
  libs/shared/services/auth/tsconfig.json
  libs/shared/services/auth/tsconfig.lib.json
  libs/shared/services/auth/tsconfig.spec.json
  libs/shell/feature/src/lib/shell-routing.module.ts
  tsconfig.base.json
  workspace.json
Labels: type:enhancement, scope:tests, scope:client, priority:medium, status:ready, type:feature

#293 Revert "Deploy testing"
  .github/workflows/CD.yml
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ContractController.java
  Server/src/main/java/Database/TheAuPair/Controllers/NotificationsController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ReportController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
  Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
  libs/shared/api/api.service.ts
  package.json
  tools/scripts/clean-build.js
Labels: scope:admin, priority:high, status:ready, type:fix

#294 (✨) : Added functionality to delete children and activities
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
  Server/src/main/java/Database/TheAuPair/Services/ChildService.java
  Server/src/test/java/Database/TheAuPair/ActivityRepositoryTests.java
  libs/add-child/feature/src/lib/add-child.component.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.html
  libs/children-dashboard/feature/src/lib/children-dashboard.component.scss
  libs/children-dashboard/feature/src/lib/children-dashboard.component.spec.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/shared/api/api.service.ts
Labels: type:enhancement, scope:api, scope:client, priority:medium, status:needs-tests

#297 ✅(CI/CD) : Deployment and hosting workflows
  .github/workflows/CD.yml
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ContractController.java
  Server/src/main/java/Database/TheAuPair/Controllers/NotificationsController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ReportController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
  Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
  Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
  libs/shared/api/api.service.ts
  package.json
  tools/scripts/clean-build.js
Labels: type:enhancement, scope:cicd, priority:high, status:ready

#298 💄Login and Registration field fixes and iOS blank background fix
  apps/the-au-pair/src/theme/variables.scss
  libs/forgot-password/feature/src/lib/forgot-password.component.scss
  libs/login/feature/src/lib/login.component.scss
  libs/register/feature/src/lib/register.component.html
  libs/register/feature/src/lib/register.component.scss
  libs/register/feature/src/lib/register.component.ts
  libs/shared/components/location-field/src/lib/location-field.component.ts
Labels: scope:ui, scope:client, priority:medium, status:ready, type:change, type:cosmetic, type:fix

#304 🔐(Enviroments) : Created Enviroments
  apps/the-au-pair/src/environments/environment.prod.ts
  apps/the-au-pair/src/environments/environment.ts
  libs/shared/api/api.service.ts
Labels: type:enhancement, scope:cicd, priority:low, status:ready

#302 💄👽️(UI+API) Report Button for users
  Server/src/main/java/Database/TheAuPair/Controllers/ReportController.java
  Server/src/main/java/Database/TheAuPair/Models/Report.java
  Server/src/main/java/Database/TheAuPair/Repositories/ReportRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ReportService.java
  Server/src/test/java/Database/TheAuPair/ReportRepositoryTests.java
  libs/admin-console/feature/src/lib/admin-console.component.spec.ts
  libs/admin-console/feature/src/lib/admin-console.component.ts
  libs/admin-reports/feature/src/lib/admin-reports.component.html
  libs/admin-reports/feature/src/lib/admin-reports.component.spec.ts
  libs/admin-reports/feature/src/lib/admin-reports.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard-feature.module.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.html
  libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.scss
  libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.ts
  libs/parent-dashboard/feature/src/lib/au-pair-rating-modal/au-pair-rating-modal.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard-feature.module.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.html
  libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.scss
  libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: type:enhancement, scope:ui, scope:api, scope:tests, scope:client, priority:high, type:feature

#305 🚨Backend test fixes preventing build
  Server/src/test/java/Database/TheAuPair/ReportRepositoryTests.java
Labels: scope:tests, priority:high, status:ready, type:tests

#306 Mobile nav V1
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/explore/feature/src/lib/explore.component.html
  libs/explore/feature/src/lib/explore.component.scss
  libs/explore/feature/src/lib/explore.component.ts
  libs/login/feature/src/lib/login.component.ts
  libs/notifications/feature/src/lib/notifications.component.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/shared/components/navbar/src/lib/navbar.component.html
  libs/shared/components/navbar/src/lib/navbar.component.scss
  libs/shared/components/navbar/src/lib/navbar.component.spec.ts
  libs/shared/components/navbar/src/lib/navbar.component.ts
  libs/shared/components/navbar/src/lib/navbar.module.ts
  libs/shared/ngxs/actions.ts
  libs/shared/ngxs/state.ts
Labels: scope:client, priority:high, status:not-ready, status:needs-tests, type:bug, type:chore, type:cosmetic

#307 Modal Fixes and Parent Dashboard buttons fix
  apps/the-au-pair/src/theme/variables.scss
  libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
  libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.scss
Labels: scope:ui, scope:client, priority:medium, type:bug, type:cosmetic

#308 ✨(Feature): Created Job Summary Pages
  apps/the-au-pair/src/theme/variables.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.ts
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.ts
  libs/hire-requests/feature/src/lib/hire-requests-feature.module.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.html
  libs/hire-requests/feature/src/lib/hire-requests.component.scss
  libs/hire-requests/feature/src/lib/hire-requests.component.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.html
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.scss
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.spec.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-au-pair-view/feature/.eslintrc.json
  libs/job-summary-au-pair-view/feature/README.md
  libs/job-summary-au-pair-view/feature/jest.config.js
  libs/job-summary-au-pair-view/feature/project.json
  libs/job-summary-au-pair-view/feature/src/index.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view-feature.module.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view-routing.module.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.html
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.scss
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.spec.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/job-summary-au-pair-view/feature/src/test-setup.ts
  libs/job-summary-au-pair-view/feature/tsconfig.json
  libs/job-summary-au-pair-view/feature/tsconfig.lib.json
  libs/job-summary-au-pair-view/feature/tsconfig.spec.json
  libs/job-summary-parent-view/feature/.eslintrc.json
  libs/job-summary-parent-view/feature/README.md
  libs/job-summary-parent-view/feature/jest.config.js
  libs/job-summary-parent-view/feature/project.json
  libs/job-summary-parent-view/feature/src/index.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view-feature.module.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view-routing.module.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.html
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.scss
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.spec.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/job-summary-parent-view/feature/src/test-setup.ts
  libs/job-summary-parent-view/feature/tsconfig.json
  libs/job-summary-parent-view/feature/tsconfig.lib.json
  libs/job-summary-parent-view/feature/tsconfig.spec.json
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/shared/components/navbar/src/lib/navbar.component.html
  libs/shell/feature/src/lib/shell-routing.module.ts
  package-lock.json
  tsconfig.base.json
  workspace.json
Labels: type:enhancement, scope:ui, scope:client, priority:high, status:ready, type:feature

#310 ✨(Feature): Parent Rating
  Server/src/main/java/Database/TheAuPair/Models/Parent.java
  Server/src/main/java/Database/TheAuPair/Models/auPair.java
  Server/src/test/java/Database/TheAuPair/ParentRepositoryTests.java
  Server/src/test/java/Database/TheAuPair/auPairRepositoryTests.java
  apps/the-au-pair/src/app/app.component.ts
  libs/add-child/feature/src/lib/add-child.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard-feature.module.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-dashboard/feature/src/lib/parent-rating-modal/parent-rating-modal.component.html
  libs/au-pair-dashboard/feature/src/lib/parent-rating-modal/parent-rating-modal.component.scss
  libs/au-pair-dashboard/feature/src/lib/parent-rating-modal/parent-rating-modal.component.ts
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.html
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.spec.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
  libs/edit-child/feature/src/lib/edit-child.component.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.ts
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.html
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.spec.ts
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.ts
  libs/explore/feature/src/lib/explore.component.html
  libs/explore/feature/src/lib/explore.component.scss
  libs/explore/feature/src/lib/explore.component.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.html
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.spec.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.html
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.html
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/parent-dashboard/feature/src/lib/au-pair-rating-modal/au-pair-rating-modal.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.html
  libs/parent-profile/feature/src/lib/parent-profile.component.ts
  libs/register/feature/src/lib/register.component.ts
  libs/shared/interfaces/interfaces.ts
  libs/track-au-pair/feature/src/lib/track-au-pair.component.ts
  tsconfig.base.json
  workspace.json
Labels: type:enhancement, scope:ui, scope:client, priority:high, status:ready, type:feature

#319 Email integration and secret/env setup
  .gitignore
  Server/pom.xml
  Server/src/main/java/Database/TheAuPair/Controllers/EmailController.java
  Server/src/main/java/Database/TheAuPair/Models/EmailRequest.java
  Server/src/main/java/Database/TheAuPair/SendGridConfigProperties.java
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
  Server/src/main/resources/application.properties
  Server/src/main/resources/secrets_template.properties
  Server/src/test/java/Database/TheAuPair/ContractRepositoryTests.java
  libs/register/feature/src/lib/register.component.spec.ts
  libs/register/feature/src/lib/register.component.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: type:enhancement, scope:api, scope:cicd, scope:repository, priority:high, status:ready, status:not-ready, type:feature, type:fix

#324 🚑️ Hotfix: Environment fix for email sending
  Server/src/main/java/Database/TheAuPair/Controllers/EmailController.java
Labels: scope:api, priority:high, status:ready, type:fix

#325 Navbar fix and navbar testing
  apps/the-au-pair/src/app/app.component.html
  apps/the-au-pair/src/app/app.component.scss
  apps/the-au-pair/src/app/app.component.spec.ts
  apps/the-au-pair/src/app/app.component.ts
  apps/the-au-pair/src/app/app.module.ts
  apps/the-au-pair/src/styles.scss
  libs/shared/components/navbar/src/lib/navbar.component.html
  libs/shared/components/navbar/src/lib/navbar.component.spec.ts
  libs/shared/components/navbar/src/lib/navbar.component.ts
  libs/shared/ngxs/state.ts
Labels: scope:ui, scope:tests, scope:client, priority:high, status:ready, type:bug, type:cosmetic, type:tests

#329 💄✨Landing Page and Nav bar
  apps/the-au-pair/src/assets/images/happy-people.svg
  apps/the-au-pair/src/assets/images/logo.svg
  apps/the-au-pair/src/assets/images/parent-dashboard-screenshot.png
  apps/the-au-pair/src/assets/images/screenshot-mobile.png
  apps/the-au-pair/src/styles.scss
  libs/landing-page/feature/.eslintrc.json
  libs/landing-page/feature/README.md
  libs/landing-page/feature/jest.config.js
  libs/landing-page/feature/project.json
  libs/landing-page/feature/src/index.ts
  libs/landing-page/feature/src/lib/landing-page-feature.module.ts
  libs/landing-page/feature/src/lib/landing-page-routing.module.ts
  libs/landing-page/feature/src/lib/landing-page.component.html
  libs/landing-page/feature/src/lib/landing-page.component.scss
  libs/landing-page/feature/src/lib/landing-page.component.spec.ts
  libs/landing-page/feature/src/lib/landing-page.component.ts
  libs/landing-page/feature/src/test-setup.ts
  libs/landing-page/feature/tsconfig.json
  libs/landing-page/feature/tsconfig.lib.json
  libs/landing-page/feature/tsconfig.spec.json
  libs/register/feature/src/lib/register.component.ts
  libs/shared/components/navbar/src/lib/navbar.component.html
  libs/shared/components/navbar/src/lib/navbar.component.scss
  libs/shared/components/navbar/src/lib/navbar.component.ts
  libs/shell/feature/src/lib/shell-routing.module.ts
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: type:enhancement, scope:ui, scope:design, scope:client, priority:high, status:ready, type:cosmetic, type:feature

#330 💄🐛✨ : Activity/Schedule enhancements and date of birth field for children
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Models/Child.java
  Server/src/main/java/Database/TheAuPair/Services/ChildService.java
  libs/add-child/feature/src/lib/add-child-feature.module.ts
  libs/add-child/feature/src/lib/add-child-routing.module.ts
  libs/add-child/feature/src/lib/add-child.component.html
  libs/add-child/feature/src/lib/add-child.component.scss
  libs/add-child/feature/src/lib/add-child.component.spec.ts
  libs/add-child/feature/src/lib/add-child.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.scss
  libs/children-dashboard/feature/src/lib/children-dashboard.component.spec.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
  libs/edit-child/feature/src/lib/edit-child.component.html
  libs/edit-child/feature/src/lib/edit-child.component.scss
  libs/edit-child/feature/src/lib/edit-child.component.spec.ts
  libs/edit-child/feature/src/lib/edit-child.component.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.scss
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/schedule/feature/src/lib/schedule.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
  libs/shared/ngxs/actions.ts
  libs/shared/ngxs/state.ts
Labels: type:enhancement, scope:api, scope:client, priority:high, status:needs-tests, type:feature

#339 ✅ (Unit Tests, UI, Bug Fixes, Enhancements) : Unit Testing, Mobile Scaling, Job Summary Enhancements
  apps/the-au-pair/src/styles.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard-feature.module.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-dashboard/feature/src/lib/parent-rating-modal/parent-rating-modal.component.ts
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.scss
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.spec.ts
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.scss
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.spec.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.html
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.scss
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.ts
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.html
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.scss
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.ts
  libs/explore/feature/src/lib/explore.component.scss
  libs/explore/feature/src/lib/explore.component.spec.ts
  libs/explore/feature/src/lib/explore.component.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.html
  libs/hire-requests/feature/src/lib/hire-requests.component.scss
  libs/hire-requests/feature/src/lib/hire-requests.component.spec.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.html
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.scss
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.html
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.scss
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.spec.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.html
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.scss
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.spec.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/parent-dashboard/feature/src/lib/au-pair-rating-modal/au-pair-rating-modal.component.html
  libs/parent-dashboard/feature/src/lib/au-pair-rating-modal/au-pair-rating-modal.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.html
  libs/parent-profile/feature/src/lib/parent-profile.component.scss
  libs/parent-profile/feature/src/lib/parent-profile.component.spec.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.ts
Labels: type:enhancement, scope:ui, scope:tests, scope:client, priority:high, status:ready, type:chore, type:fix, type:tests

#340 Email sends,basic loaders and locations fixes
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Repositories/ParentRepository.java
  Server/src/main/java/Database/TheAuPair/Services/ParentService.java
  Server/src/main/java/Database/TheAuPair/Services/UserService.java
  apps/the-au-pair/src/styles.scss
  apps/the-au-pair/src/theme/variables.scss
  libs/add-child/feature/src/lib/add-child.component.ts
  libs/admin-console/feature/src/lib/admin-console.component.ts
  libs/admin-reports/feature/src/lib/admin-reports.component.spec.ts
  libs/admin-reports/feature/src/lib/admin-reports.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.html
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.scss
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.html
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.scss
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/login/feature/src/lib/login.component.html
  libs/login/feature/src/lib/login.component.scss
  libs/login/feature/src/lib/login.component.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/register/feature/src/lib/register.component.html
  libs/register/feature/src/lib/register.component.scss
  libs/register/feature/src/lib/register.component.ts
  libs/shared/api/api.service.ts
  libs/shared/components/location-field/src/lib/location-field.component.html
  libs/shared/components/location-field/src/lib/location-field.component.scss
  libs/shared/components/location-field/src/lib/location-field.component.ts
  libs/shared/components/navbar/src/lib/navbar.component.ts
  libs/shared/ngxs/actions.ts
  libs/shared/ngxs/state.ts
Labels: scope:client, priority:high, status:ready, type:feature, type:fix

#345 💚(Deployment): Updated Deployment
  .github/workflows/CD.yml
  apps/the-au-pair/src/environments/environment.prod.ts
Labels: scope:admin, priority:high, status:ready, type:fix

#346 ✨(AWS Storage): API functionality for app storage
  Server/pom.xml
  Server/src/main/java/Database/TheAuPair/Controllers/StorageController.java
  Server/src/main/java/Database/TheAuPair/S3Config.java
  Server/src/main/java/Database/TheAuPair/Services/StorageService.java
  Server/src/main/resources/application.properties
  libs/shared/api/api.service.ts
Labels: scope:database, priority:high, status:ready, type:feature

#354 Dynamic Push notifications for mobile
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Services/UserService.java
  Server/src/main/resources/secrets_template.properties
  apps/the-au-pair/src/app/app.component.ts
  libs/login/feature/src/lib/login.component.spec.ts
  libs/login/feature/src/lib/login.component.ts
  libs/shared/api/api.service.ts
Labels: scope:ui, scope:client, priority:high, status:ready

#355 (👽️💄) : Notification when au pairs are out of bounds and automatically toggle onShift for au pairs
  Server/src/main/java/Database/TheAuPair/Models/Activity.java
  Server/src/main/java/Database/TheAuPair/Models/auPair.java
  Server/src/test/java/Database/TheAuPair/ActivityRepositoryTests.java
  Server/src/test/java/Database/TheAuPair/auPairRepositoryTests.java
  apps/the-au-pair/src/app/app.component.ts
  apps/the-au-pair/src/assets/images/no-image.png
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.ts
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.scss
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.spec.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/notifications/feature/src/lib/notifications.component.scss
  libs/notifications/feature/src/lib/notifications.component.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-dashboard/feature/src/lib/au-pair-rating-modal/au-pair-rating-modal.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.spec.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.html
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.scss
  libs/parent-view-activity/feature/src/lib/parent-view-activity.component.ts
  libs/register/feature/src/lib/register.component.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/schedule/feature/src/lib/schedule.ts
  libs/shared/interfaces/interfaces.ts
  libs/track-au-pair/feature/src/lib/track-au-pair.component.ts
Labels: type:enhancement, scope:ui, scope:api, scope:client, priority:high, status:needs-tests, type:fix

#356 ✅ (Unit Tests, UI, Bug Fixes, Enhancements) : Unit Testing, Notifications
  apps/the-au-pair/src/app/app.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.html
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.scss
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.spec.ts
  libs/au-pair-profile/feature/src/lib/au-pair-profile.component.ts
  libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.spec.ts
  libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.spec.ts
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.html
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.scss
  libs/explore/feature/src/lib/expand-modal/expand-modal.component.ts
  libs/explore/feature/src/lib/explore.component.html
  libs/explore/feature/src/lib/explore.component.spec.ts
  libs/explore/feature/src/lib/explore.component.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.spec.ts
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.html
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.html
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.spec.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.html
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.spec.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.html
  libs/parent-profile/feature/src/lib/parent-profile.component.scss
  libs/parent-profile/feature/src/lib/parent-profile.component.spec.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.ts
Labels: type:enhancement, scope:ui, scope:database, scope:tests, scope:client, priority:high, status:ready, type:chore, type:fix, type:tests

#357 💚(Deployment and Hosting): Updated CD and added testing endpoint
  .github/workflows/CD.yml
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
Labels: scope:cicd, priority:high, status:ready, type:fix

#347 👔👽️✅💄(Logic + API + Tests + UI) Added Cost adding/removing/viewing system for users
  .github/workflows/CD.yml
  Server/src/main/java/Database/TheAuPair/Controllers/FuelCostController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserCostsController.java
  Server/src/main/java/Database/TheAuPair/Models/UserCosts.java
  Server/src/main/java/Database/TheAuPair/Repositories/UserCostsRepository.java
  Server/src/main/java/Database/TheAuPair/Services/UserCostsService.java
  Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
  Server/src/main/resources/secrets_template.properties
  Server/src/test/java/Database/TheAuPair/UserCostsRepositoryTests.java
  apps/the-au-pair/project.json
  libs/au-pair-cost/feature/src/lib/au-pair-cost-feature.module.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.html
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.scss
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
  libs/au-pair-cost/feature/src/lib/edit-rate-modal/edit-rate-modal.component.html
  libs/au-pair-cost/feature/src/lib/edit-rate-modal/edit-rate-modal.component.scss
  libs/au-pair-cost/feature/src/lib/edit-rate-modal/edit-rate-modal.component.ts
  libs/au-pair-cost/feature/src/lib/extra-costs-modal/extra-costs-modal.component.html
  libs/au-pair-cost/feature/src/lib/extra-costs-modal/extra-costs-modal.component.scss
  libs/au-pair-cost/feature/src/lib/extra-costs-modal/extra-costs-modal.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/register/feature/src/lib/register.component.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/interfaces.ts
Labels: scope:ui, scope:design, scope:api, scope:database, scope:tests, scope:client, priority:high, type:bug, type:change, type:cosmetic, type:feature, type:tests

#358 🐛🩹 Registration and UI fixes
  apps/the-au-pair/src/theme/variables.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.scss
  libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/register/feature/src/lib/register.component.html
  libs/register/feature/src/lib/register.component.spec.ts
  libs/register/feature/src/lib/register.component.ts
Labels: scope:ui, scope:design, priority:low, type:bug, type:change, type:fix

#361 👽️🐛(API + Bugs) Changed Pie Graph to update with new costs and fixed total costs
  .sonarcloud.properties
  Server/src/main/java/Database/TheAuPair/Controllers/UserCostsController.java
  Server/src/main/java/Database/TheAuPair/Repositories/UserCostsRepository.java
  Server/src/main/java/Database/TheAuPair/Services/UserCostsService.java
  Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.html
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
  libs/au-pair-cost/feature/src/lib/edit-rate-modal/edit-rate-modal.component.ts
  libs/shared/api/api.service.ts
Labels: type:enhancement, scope:ui, scope:api, scope:client, priority:high, type:bug, type:change

#370 💄 (UI) : Fixed UI, Updated Terms of Employment, Updated Job Summary
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.html
  libs/children-dashboard/feature/src/lib/children-dashboard.component.spec.ts
  libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
  libs/hire-requests/feature/src/lib/hire-requests.component.html
  libs/hire-requests/feature/src/lib/job-summary-modal/job-summary-modal.component.html
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.html
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.scss
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.spec.ts
  libs/job-summary-au-pair-view/feature/src/lib/job-summary-au-pair-view.component.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.html
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.scss
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.spec.ts
  libs/job-summary-parent-view/feature/src/lib/job-summary-parent-view.component.ts
  libs/login/feature/src/lib/login.component.html
  libs/login/feature/src/lib/login.component.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
  libs/parent-profile/feature/src/lib/parent-profile.component.html
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/schedule/feature/src/lib/schedule.ts
Labels: type:enhancement, scope:ui, scope:client, priority:medium, status:ready, type:chore, type:fix

#372 ✅(Testing): Updated and Added Cypress tests
  Server/src/main/java/Database/TheAuPair/Controllers/FuelCostController.java
  cypress.json
  cypress/integration/admin-integration-tests.spec.js
  cypress/integration/aupair-integration-tests.spec.js
  cypress/integration/parent-integration.spec.js
  cypress/integration/user-integration-tests.spec.js
  libs/shared/components/navbar/src/lib/navbar.component.html
Labels: scope:tests, priority:medium, status:ready, type:tests

#378 ✅Added more testing to increase coverage
  apps/the-au-pair/src/app/app.component.spec.ts
  apps/the-au-pair/src/app/app.component.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
Labels: scope:tests, priority:medium, type:tests

#380 Landing page swiper updates
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Aupair/au-pair-calendar-screenshot.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Aupair/au-pair-costs.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Aupair/au-pair-dashboard-screenshot.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Aupair/au-pair-job-summary.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Parent/parent-add-children.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Parent/parent-calendar.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Parent/parent-costs.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Parent/parent-dashboard.png
  apps/the-au-pair/src/assets/images/Desktop-screenshots/Parent/parent-tracking.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Aupair/au-pair-calendar-mobile.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Aupair/au-pair-costs-mobile.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Aupair/au-pair-dashboard-mobile.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Aupair/au-pair-job-summary-mobile.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Parent/parent-children.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Parent/parent-costs.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Parent/parent-dashboard.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Parent/parent-schedule.png
  apps/the-au-pair/src/assets/images/Mobile-screenshots/Parent/parent-tracking.png
  apps/the-au-pair/src/assets/images/parent-dashboard-screenshot.png
  apps/the-au-pair/src/assets/images/screenshot-mobile.png
  libs/landing-page/feature/src/lib/landing-page.component.html
Labels: scope:ui, scope:client, priority:high, type:cosmetic

#381 💄🐛: UI and Bug fixes from usability testing feedback
  apps/the-au-pair/src/app/app.component.html
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.scss
  libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
  libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
  libs/shared/components/navbar/src/lib/navbar.component.html
Labels: scope:client, priority:high, status:ready, type:cosmetic, type:fix

#383 🎨(Version Control)
  .github/workflows/CD.yml
  Server/pom.xml
Labels: scope:admin, priority:high, status:ready, type:chore
