Repository COS301-SE-2022/The-Au-Pair, pull requests merged in 2022-05, with the labels that each got.

#24 ✅ (CI/CD) : Linter
  .github/workflows/workflows copy/index.yml
  .github/workflows/workflows copy/lint.yml
Labels: scope:cicd, priority:high, status:ready, type:feature

#33 🎉(Backend) : Initialize backend Spring-boot project
  Server/.gitignore
  Server/.mvn/wrapper/maven-wrapper.jar
  Server/.mvn/wrapper/maven-wrapper.properties
  Server/mvnw
  Server/mvnw.cmd
  Server/pom.xml
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
  Server/src/main/resources/application.properties
  Server/src/test/java/Database/TheAuPair/TheAuPairApplicationTests.java
Labels: scope:repository, priority:high, status:ready, type:feature

#36 ✅(CI/CD) : Completed Pipeline
  .github/workflows/CI.yml
  .github/workflows/Full.yml
  .github/workflows/index.yml
  .github/workflows/workflows copy/index.yml
  .github/workflows/workflows copy/lint.yml
Labels: scope:cicd, priority:high, status:ready, type:feature

#40 🚧(Backend) : Models and Repositories
  Server/src/main/java/Database/TheAuPair/Models/Activity.java
  Server/src/main/java/Database/TheAuPair/Models/Child.java
  Server/src/main/java/Database/TheAuPair/Models/Parent.java
  Server/src/main/java/Database/TheAuPair/Models/User.java
  Server/src/main/java/Database/TheAuPair/Models/auPair.java
  Server/src/main/java/Database/TheAuPair/Models/medID.java
  Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/ParentRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/UserRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/auPairRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/medAidRepository.java
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
  Server/src/main/resources/application.properties
Labels: type:enhancement, scope:api, priority:high, status:ready

#44 Added Colour Themes for Ionic
  apps/the-au-pair/src/theme/variables.scss
Labels: scope:ui, scope:design, priority:medium, status:ready, type:cosmetic

#41 Schedule UI
  apps/the-au-pair/src/index.html
  apps/the-au-pair/src/styles.scss
  apps/the-au-pair/src/theme/variables.scss
  libs/schedule/feature/.eslintrc.json
  libs/schedule/feature/README.md
  libs/schedule/feature/jest.config.js
  libs/schedule/feature/project.json
  libs/schedule/feature/src/index.ts
  libs/schedule/feature/src/lib/activity-card/activity-card.component.html
  libs/schedule/feature/src/lib/activity-card/activity-card.component.scss
  libs/schedule/feature/src/lib/activity-card/activity-card.component.spec.ts
  libs/schedule/feature/src/lib/activity-card/activity-card.component.ts
  libs/schedule/feature/src/lib/schedule-feature.module.ts
  libs/schedule/feature/src/lib/schedule-routing.module.ts
  libs/schedule/feature/src/lib/schedule.component.spec.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/schedule/feature/src/lib/schedule.ts
  libs/schedule/feature/src/test-setup.ts
  libs/schedule/feature/tsconfig.json
  libs/schedule/feature/tsconfig.lib.json
  libs/schedule/feature/tsconfig.spec.json
  libs/shared/assets/fonts/roboto.woff2
  libs/shared/assets/fonts/titan1.woff2
  libs/shell/feature/src/lib/shell-routing.module.ts
  package-lock.json
  tsconfig.base.json
  workspace.json
Labels: scope:ui, scope:client, priority:medium, status:ready, type:cosmetic, type:feature

#48 💄(UI): Add Activity Static page
  apps/the-au-pair/src/assets/images/active-2.png
  apps/the-au-pair/src/assets/images/active.png
  apps/the-au-pair/src/assets/images/lifestyles.png
  libs/parent-add-activity/feature/.eslintrc.json
  libs/parent-add-activity/feature/README.md
  libs/parent-add-activity/feature/jest.config.js
  libs/parent-add-activity/feature/project.json
  libs/parent-add-activity/feature/src/index.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity-feature.module.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity-routing.module.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/parent-add-activity/feature/src/test-setup.ts
  libs/parent-add-activity/feature/tsconfig.json
  libs/parent-add-activity/feature/tsconfig.lib.json
  libs/parent-add-activity/feature/tsconfig.spec.json
  libs/shell/feature/src/lib/shell-routing.module.ts
  tsconfig.base.json
  workspace.json
Labels: scope:ui, priority:high, status:ready, type:feature

#49 ✅(CI/CD) : Pipeline Update
  .github/workflows/CI.yml
  README.md
  jest.preset.js
  tools/scripts/merge-report.js
Labels: type:enhancement, scope:cicd, priority:high, status:ready

#50 🚑️(Hotfix) : script rename
  .github/workflows/CI.yml
Labels: scope:cicd, priority:high, status:ready, type:fix

#53 💄 UI: Created the Parent Dashboard
  apps/the-au-pair-e2e/src/integration/app.spec.ts
  apps/the-au-pair/src/app/app.component.html
  apps/the-au-pair/src/theme/variables.scss
  libs/parent-dashboard/feature/.eslintrc.json
  libs/parent-dashboard/feature/README.md
  libs/parent-dashboard/feature/jest.config.js
  libs/parent-dashboard/feature/project.json
  libs/parent-dashboard/feature/src/index.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard-feature.module.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard-routing.module.ts
  libs/parent-dashboard/feature/src/lib/parent-dashboard.html
  libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
  libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
  libs/parent-dashboard/feature/src/test-setup.ts
  libs/parent-dashboard/feature/tsconfig.json
  libs/parent-dashboard/feature/tsconfig.lib.json
  libs/parent-dashboard/feature/tsconfig.spec.json
  libs/shell/feature/src/lib/shell-routing.module.ts
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: scope:ui, priority:high, status:ready, type:cosmetic, type:feature

#54 👽️(API) : Initial API
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
  Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
  Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
  Server/src/main/java/Database/TheAuPair/Models/Activity.java
  Server/src/main/java/Database/TheAuPair/Models/medAid.java
  Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/ParentRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/UserRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/auPairRepository.java
  Server/src/main/java/Database/TheAuPair/Repositories/medAidRepository.java
  Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
  apps/the-au-pair/src/app/app.module.ts
  libs/shared/api/api.service.ts
  libs/shared/interfaces/activity.interfaces.ts
Labels: scope:api, priority:high, status:ready, type:feature

#55 🎨(API) : Function rename
  libs/shared/api/api.service.ts
Labels: scope:api, priority:low, status:ready, type:fix

#56 💄 UI: Created Au Pair Cost Page
  apps/the-au-pair/project.json
  apps/the-au-pair/src/theme/variables.scss
  libs/au-pair-cost/feature/.eslintrc.json
  libs/au-pair-cost/feature/README.md
  libs/au-pair-cost/feature/jest.config.js
  libs/au-pair-cost/feature/project.json
  libs/au-pair-cost/feature/src/index.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost-feature.module.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost-routing.module.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.html
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.scss
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
  libs/au-pair-cost/feature/src/test-setup.ts
  libs/au-pair-cost/feature/tsconfig.json
  libs/au-pair-cost/feature/tsconfig.lib.json
  libs/au-pair-cost/feature/tsconfig.spec.json
  libs/shell/feature/src/lib/shell-routing.module.ts
  tsconfig.base.json
  workspace.json
Labels: scope:ui, scope:design, priority:high, status:ready, type:cosmetic, type:feature

#58 🎨(API) : Field added to interface
  libs/shared/interfaces/activity.interfaces.ts
Labels: scope:api, priority:low, status:ready, type:fix

#59 💄✅(UI + Unit tests): Add Activity - Error checking for input fields and unit tests
  libs/parent-add-activity/feature/src/lib/parent-add-activity-feature.module.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  package.json
Labels: scope:ui, scope:tests, scope:client, priority:medium, status:needs-info, type:chore, type:tests

#62 👽️(API) : Added new service
  Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
  Server/src/main/java/Database/TheAuPair/Repositories/ParentRepository.java
  libs/shared/api/api.service.ts
Labels: scope:api, priority:medium, status:ready, type:change

#64 ✨ UI: Backend Implementation for Au Pair Cost feature
  libs/au-pair-cost/feature/src/lib/au-pair-cost-feature.module.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.html
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.scss
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
Labels: type:enhancement, scope:ui, scope:api, priority:high, status:ready, type:change, type:feature

#66 💄 👽️(UI + API usage): Add Activity - Dynamically populate fields using API
  libs/parent-add-activity/feature/src/lib/parent-add-activity-feature.module.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
  libs/shared/api/api.service.ts
  package.json
Labels: type:enhancement, scope:ui, scope:client, priority:high, status:ready, type:tests

#69 ✅(Tests) : Unit testing for backend
  Server/src/test/java/Database/TheAuPair/ActivityRepositoryTests.java
  Server/src/test/java/Database/TheAuPair/ParentRepositoryTests.java
  Server/src/test/java/Database/TheAuPair/TheAuPairApplicationTests.java
  Server/src/test/java/Database/TheAuPair/UserRepositoryTests.java
  Server/src/test/java/Database/TheAuPair/auPairRepositoryTests.java
Labels: scope:tests, priority:high, status:ready, type:tests

#71 👽️(API) : ID generation
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
Labels: scope:api, priority:high, status:ready, type:feature

#72 🗃️(API) : Updated Query
  Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
  Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
  Server/src/test/java/Database/TheAuPair/ActivityRepositoryTests.java
Labels: scope:api, priority:high, status:ready, type:fix

#75 👽️ (API): Integrated Schedule with API
  libs/schedule/feature/src/lib/activity-card/activity-card.component.html
  libs/schedule/feature/src/lib/activity-card/activity-card.component.scss
  libs/schedule/feature/src/lib/activity-card/activity-card.component.spec.ts
  libs/schedule/feature/src/lib/activity-card/activity-card.component.ts
  libs/schedule/feature/src/lib/schedule-feature.module.ts
  libs/schedule/feature/src/lib/schedule.component.spec.ts
  libs/schedule/feature/src/lib/schedule.html
  libs/schedule/feature/src/lib/schedule.scss
  libs/schedule/feature/src/lib/schedule.ts
  libs/schedule/feature/tsconfig.json
Labels: scope:api, scope:client, priority:high, status:ready, type:change

#76 🚑️(Hotfix): Fixed time-slot for earlier times
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
Labels: scope:ui, scope:client, priority:high, status:ready, type:fix

#77 🚑️(Hotfix): Hotfix for tests
  libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
  libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
Labels: scope:tests, scope:client, priority:high, status:ready, type:fix

#80 📝: README updated
  README.md
Labels: type:documentation, scope:admin, scope:repository, priority:low, status:ready, type:change

#82 🔨(Repo) : Rename of command
  package.json
Labels: scope:repository, priority:low, status:ready, type:chore

#84 🔀(Repository) : Merge release/demo1 -> develop
  package.json
Labels: scope:admin, priority:high, status:ready, type:chore
